### ISSUE TITLE
Fastlane >= 2.76.1 with slack-notifier 2.3.2 conflict

### ISSUE THREAD

**Issue by shadzik** [nakiostudio/xcov#104]
Hey,

seems the latest (as of writing this) Fastlane version 2.76.1 needs slack-notifier 2.3.2 but xcov 1.3.x still depends on slack-notifier ~> 1.3.

Could you please update that dependency so slack notifications work again? Thanks!

**Comment by johnmillz** [comment]
It's actually >=2.76.0 which has the conflict see:

https://github.com/fastlane/fastlane/pull/11465/files

**Comment by nakiostudio** [comment]
Just released `1.3.2`. Thanks @thelvis4 for the fix and the rest of you for your patience.

**Comment by pertau** [comment]
I'm sorry, we use Fastlane version 2.83 with Xcov version 1.3.2 and slack-notifier plugin 2.3.2. 

Since the update to fastlane version 2.83, our Xcov Slack Notification ignores the "slack_username" and "slack_channel" properties. 

Do you have any ideas, how to fix this problem?
