### ISSUE TITLE
--derived_data_path option not being used

### ISSUE THREAD

**Issue by apocolipse** [nakiostudio/xcov#11]
The `--derived_data_path` option is not being respected, in `lib/xcov/runner.rb` it attempts to find `.xccoverage` files only by looking at the .xcodeproj files, [Source](https://github.com/nakiostudio/xcov/blob/master/lib/xcov/runner.rb#L20-23)

Searching for `derived_data_path` and even `XCOV_DERIVED_DATA_PATH` in the codebase only yields the setting in `lib/xcov/options.rb`

This currently interferes with fastlane's `setup_jenkins` action which sets the derived data path to a jenkins workspace relative path, so that when running xcov it fails with the following:
```
ERROR [2016-03-10 00:02:50.02]: Unable to find any .xccoverage file.
ERROR [2016-03-10 00:02:50.02]: Make sure you have enabled 'Gather code coverage' setting on your scheme settings.
ERROR [2016-03-10 00:02:50.02]: Alternatively you can provide the full path to your .xccoverage file.
```

**Comment by nakiostudio** [comment]
Hi @apocolipse. You are absolutely right, I'm going to fix it asap.
I will keep you updated, thanks for reporting :+1

**Comment by nakiostudio** [comment]
Hi @apocolipse. I've just released the version 0.5 fixing this issue and another one. Please let me know if the update solves your problem :)

**Comment by nakiostudio** [comment]
Example of use:

```
xcov -w LystSDK.xworkspace -s LystSDK -j /Users/nakiostudio/Library/Developer/Xcode/DerivedData/LystSDK-fdtwgbzpiwhsxtbyxrzdtlylrgkp
```

**Comment by apocolipse** [comment]
:+1: thanks @nakiostudio, just re-enabled `setup_jenkins` in my fastlane config and set up xcov and all is good.
Closing the issue

**Comment by nakiostudio** [comment]
Great :)
