### ISSUE TITLE
Unable to find any .xccoverage file

### ISSUE THREAD

**Issue by Blackjacx** [nakiostudio/xcov#111]
Hey there, 

I got this issue today. I just set the Xcode version to 9.3 and it seemed they changed some settings concerning the code coverage. The screen now looks like this:

![screen shot 2018-04-03 at 14 09 47](https://user-images.githubusercontent.com/794372/38248452-b75d9834-3748-11e8-8380-a39aaeac174b.png)

And also when I have a look in the DerivedData folder I can find these files:

![screen shot 2018-04-03 at 14 07 56](https://user-images.githubusercontent.com/794372/38248476-c9678846-3748-11e8-85b5-f939cb8803d3.png)

But there is no `xccoverage` anymore. Maybe they changed the name/format of the coverage file.

Can you confirm this?

**Comment by davevdveen** [comment]
https://github.com/nakiostudio/xcov-core/issues/12

**Comment by Blackjacx** [comment]
Works like a charm 👍

**Comment by rajeshchilukuri** [comment]
even though  I am not using legacy_support its giving me error Unable to find any .xccoverage file.
