### ISSUE TITLE
Use Xcode 9.3's built-in xccov tool

### ISSUE THREAD

**Issue by chrisballinger** [nakiostudio/xcov#122]
For example:

```
$ xcrun xccov view --only-targets --json Build/Logs/Test/*.xccovreport > result.json
```

There's already another gem that helps parse the json reports: https://github.com/KazuCocoa/xccov-parse

**Comment by nakiostudio** [comment]
Hi @chrisballinger 👋 

Thanks for opening the issue :)

xcov already uses the  `IDEFoundation` utilities that xccov uses under the hood therefore switching to xccov wouldn't add any value. You can find more details on this [here](https://github.com/nakiostudio/xcov-core/issues/12).

**Comment by chrisballinger** [comment]
Ahh cool. Thanks!
