### ISSUE TITLE
xcov linesCovered differs greatly from xccov view --json

### ISSUE THREAD

**Issue by swhitty** [nakiostudio/xcov#127]
When upgrading from Xcode 9.2 -> Xcode 9.3 I am noticing that xcov is now reporting linesCovered figures that differ greatly from what Xcode reports.

I have also verified that the reported lineCovered does not align with the `xcrun xccov view` json report. 

`% xcrun xccov view ${DERIVED_DATA}/Logs/Test/*.xccovreport --json > report.json`

From the attached project it appears the the reported xcov total linesCovered is including lines within the xctest target also.
[CoverageTest-9.3.zip](https://github.com/nakiostudio/xcov/files/2007550/CoverageTest-9.3.zip)

Xcode Reports: 57.14%
xcov Reports: 75%
[reports.zip](https://github.com/nakiostudio/xcov/files/2007621/reports.zip)

**Comment by nakiostudio** [comment]
Hey @swhitty, thanks for reporting and taking the time of creating the test project.

The issue here is that xcov is calculating the coverage with the average file coverage whereas Xcode is using the average function coverage. I will push a fix ASAP.

**Comment by nakiostudio** [comment]
Hi again @swhitty 👋 

Sorry for the delay getting this fixed. I've just released xcov `1.4.3` that tackles this issue.
