### ISSUE TITLE
The Percentage code coverage is more as compare to Xcode coverage percentage.

### ISSUE THREAD

**Issue by sandeee1928** [nakiostudio/xcov#131]
I'm using `xcov` with `fastlane` but the percentage coverage showing is more as compare to Xcode coverage percentage.

`xcov version: 1.4.2`

![screen shot 2018-06-22 at 11 34 13 am](https://user-images.githubusercontent.com/2527526/41793482-15b92680-7611-11e8-934d-bb56b35e177b.png)
<img width="369" alt="screen shot 2018-06-22 at 11 35 01 am" src="https://user-images.githubusercontent.com/2527526/41793483-15d61b32-7611-11e8-962d-7e9a846b4f17.png">

**Comment by nakiostudio** [comment]
Hi @sandeee1928 

This issue was fixed recently. Upgrade to ‘1.4.3’ and you should get the same coverage as Xcode reports.
