### ISSUE TITLE
.xcovignore does not allow wildcard

### ISSUE THREAD

**Issue by stevenreinisch** [nakiostudio/xcov#15]
Hej,

if I add a file name with a wildcard like this:

`- *View.swift`

no file listed in .xcovignore is not ignored.

Is it possible to use wildcards?

cheers,

steven

**Comment by nakiostudio** [comment]
Hey :wave: 

That's not supported but it's interesting. I will support the matching of that kind of pattern for the next release :+1:

**Comment by stevenreinisch** [comment]
That's awesome!

**Comment by nakiostudio** [comment]
Closing this thanks to you @stevenreinisch 👍
