### ISSUE TITLE
1.5.1 Release?

### ISSUE THREAD

**Issue by chrisballinger** [nakiostudio/xcov#152]
I'm interested in using the new `xccov_file_direct_path` flag but it seems the functionality is only available on the master branch. Is there a plan for publishing the next release to RubyGems? 

Cheers!

**Comment by cianiandreadev** [comment]
+1

**Comment by cianiandreadev** [comment]
@nakiostudio I saw that latest updated (1.5) is being released last year. Would be possible to have this minor release? In my team we are all looking forward for the #150 :)

**Comment by nakiostudio** [comment]
Thanks for your patience. 1.5.1 has been pushed now.
