### ISSUE TITLE
You cannot ignore a subproject

### ISSUE THREAD

**Issue by mike011** [nakiostudio/xcov#16]
**Expectation**
I don't want to see the sub project in the code coverage report. 

**Setup**
I have a project with an imported subproject

**What I've Tried**
- Adding all the source files that the subproject contains to the .xcovignore ignore file, or the project name, or the base folder the project is still shown.
- There doesn't seem to be another option to ignore subprojects

**Comment by nakiostudio** [comment]
Hi @mike011 :wave: 

I see the point of your request, I will try to implement it for the next release of xcov :+1:

**Comment by stevenreinisch** [comment]
Hi @mike011,

can you check if my [PR](https://github.com/nakiostudio/xcov/pull/17) solves your issue? I was facing the same issue with a sub project.

cheers

**Comment by nakiostudio** [comment]
Closing it as #18 with the great work of @stevenreinisch implements the feature
