### ISSUE TITLE
Many projects with lots of targets

### ISSUE THREAD

**Issue by mapedd** [nakiostudio/xcov#23]
Hi amigos! Thanks for this amazing tool!

I'm trying to use it with quite big project. It's a massive `xcworkspace` with more than  10 projects and couple dozen app, library, framework and unit test targets.

What I'd like to do is to generate xcov report for all the targets that were unit tested. 

The scenario would be:

1. I run few unit test targets with "Gather Code Coverage" set to true with xcodebuild.
2. I run xcov to generate summary report from all `xccoverage` files in the `Logs/Test` directory

Is it possible to run the tool this way? I was also trying to pass path to xccoverage files directly to the tool, didn't work.

Last question - why repo contains only binary for `xcov-core` ? How are you actually parsing xcoverage files?

**Comment by nakiostudio** [comment]
Hi @mapedd 👋 

Sorry for the delay but finally I have some time available to catch up with the issues.

Your case seems a bit particular and I'm not sure if I totally understand what you want to achieve. xcov can process a single .xccoverage file at a time, but a single .xccoverage file can gather reports for different targets therefore I don't know why you are not able to do this. If you have many projects you can run the gem for each one of these but eventually that would generate a HTML report per .xccoverage file.

About xcov-core, that's the binary that actually parses the .xccoverage file, you can dig a bit more into that by checking its repository: https://github.com/nakiostudio/xcov-core

Thanks!
