### ISSUE TITLE
Integration with fastlane is broken 

### ISSUE THREAD

**Issue by daniel-beard** [nakiostudio/xcov#24]
- Fastlane core Helper removed the `.log` interface in this commit: https://github.com/fastlane/fastlane/commit/c23f35790ac49d2b96978f5200d71eae85995501
- Result is that calling the `xcov` action from fastlane no longer works.

**Comment by nakiostudio** [comment]
Hi @daniel-beard 👋, thanks for reporting.  A fix for this is almost ready, I will let you know as soon as I release 0.8.

**Comment by daniel-beard** [comment]
Thanks for the fast reply!

**Comment by nakiostudio** [comment]
Done @daniel-beard, let me know if still having the same issue 👍
