### ISSUE TITLE
Ignore files doesn't work

### ISSUE THREAD

**Issue by RedPlumber** [nakiostudio/xcov#34]
Hi I have the following configuration: 

```
lane :unit_tests do
			scan(
				scheme: get_project_name,
				destination: 'platform=iOS Simulator,name=iPhone 6,OS=9.0',
				code_coverage: true,
				output_directory: "fastlane/test_results/"
			)


			xcov(
  				workspace: "TestProject.xcworkspace",
  				scheme: "TestProject",
  				html_report: true,
  				skip_slack: true,
  				ignore_file_path: "./fastlane/.xcovignore",
  				output_directory: "xcov_output"
			)  
	end

```
How do I ignore an entire folder?

**Comment by nakiostudio** [comment]
Hey @RedPlumber 👋 

I've managed to make it work in my CI but there is definitely something wrong with it. I'm gonna take a look. Thanks for reporting!

**Comment by nakiostudio** [comment]
Regarding how to ignore a folder there is no way right now as only filename is taken in to account.

**Comment by nakiostudio** [comment]
Hi again @RedPlumber,

I've been debugging this and seems working fine. I guess the path you are passing to `ignore_file_path` might not be the right one. As the default path is `fastlane/.xcovignore`, what happens if you just remove this line? `ignore_file_path: "./fastlane/.xcovignore",`
