### ISSUE TITLE
updated fastlane-core dependency

### ISSUE THREAD

**Issue by valeriomazzeo** [nakiostudio/xcov#38]
A project using xcov cannot install the latest version of fastlane 1.101.0 because of the hard dependency on fastlanecore.

A solution would be to update this dependency:
`spec.add_dependency 'fastlane_core', '>= 0.44.0', '< 1.0.0'`

**Comment by valeriomazzeo** [comment]
Thank you @nakiostudio 👍

**Comment by nakiostudio** [comment]
Hi @valeriomazzeo 👋 

Thanks for reporting it! I've just merged #39 fixing this 🍻
