### ISSUE TITLE
No results!

### ISSUE THREAD

**Issue by RafaelPlantard** [nakiostudio/xcov#44]
The code coverage for the app is not generated.

**Comment by thelvis4** [comment]
@RafaelPlantard Could you, please, provide more details on this, like for example:
* Xcode version
* How did you run the tests? Have you set *Gather coverage data* on your scheme settings window.
* Has `.xccoverage` file been generated?

Also, isn't this, by any chance, the same case as #22?
Thanks!

**Comment by RafaelPlantard** [comment]
I'm so sorry, I already solved that problem, just forget to close it.
