### ISSUE TITLE
Project's code coverage should respect number of lines per framework.

### ISSUE THREAD

**Issue by mpodeszwa** [nakiostudio/xcov#51]
First of all, I really like this project. However I think calculating project's code coverage by simply averaging libraries' code coverages can be misleading. In my opinion it should be calculated using formula `total number of lines covered / total number of lines`.

Furthermore I would love to see `[number of lines covered] / [number of lines]` in reports as well.

**Comment by thelvis4** [comment]
@mpodeszwa Yeah, I must admit that calculating project's coverage by averaging target coverages might lead to misleading numbers. The thing is, this is the only way we could calculate project's coverage using the current input (from `xcov-core`). Currently, `xcov-core` doesn't provide the information about lines/covered lines.
I'm looking into adding the support for lines to `xcov-core`, though. Once we have that, we can change the way we calculate project's coverage.

**Comment by thelvis4** [comment]
> Furthermore I would love to see [number of lines covered] / [number of lines] in reports as well.

Regarding displaying the info about the number of lines in reports, I'm not sure it's a must-have feature for everyone.
We might implement it in a way that could be activated with a boolean parameter, which will be false by default.
Also not sure where and how we should display the info (I'm especially concerned about the HTML report).

@nakiostudio Any insights about this?

**Comment by tikitu** [comment]
If a data-point is useful: for me the new calculation method is important, the reporting is a nice-to-have but not crucial. (Seems like you're working on it already, but if I can help landing it please shout.)
