### ISSUE TITLE
Issues running on Fastlane >= 1.105.0

### ISSUE THREAD

**Issue by mramsden** [nakiostudio/xcov#54]
We're seeing the following error coming up when running the xcov action:

`Could not find option for key :configuration. Available keys: workspace, project, scheme, derived_data_path, output_directory, html_report, markdown_report, json_report, minimum_coverage_percentage, ignore_file_path, include_test_targets, slack_url, slack_channel, skip_slack, exclude_targets`

The stacktrace indicates that this is happening in https://github.com/nakiostudio/xcov/blob/master/lib/xcov.rb#L25 when it's verifying the options bundle.

This appears to happen when fastlane_core is upgraded to 0.57.0 as an internal dependency of Fastlane.

Do you have any pointers?

**Comment by thelvis4** [comment]
@mramsden Thanks for notifying us! 
Updating `fastlane-core` to 0.57.0 definitely breaks `xcov`.
I've taken a quick look and it seems to be related to https://github.com/fastlane/fastlane/pull/6114.

`xcov` doesn't have `configuration` option, which is needed by `fastlane_core` now.
As a quick fix, I'll just add `configuration` as a optional parameter.
