### ISSUE TITLE
updated fastlane-core dependency

### ISSUE THREAD

**Issue by valeriomazzeo** [nakiostudio/xcov#57]
A project using xcov cannot install the latest version of fastlane 1.111.0 because of the hard dependency on fastlanecore.

A solution would be to update this dependency:
`spec.add_dependency 'fastlane_core', '>= 0.44.0', '< 1.0.0'`

same as https://github.com/nakiostudio/xcov/issues/38

**Comment by nakiostudio** [comment]
Hey @valeriomazzeo 👋 

Thanks for reporting. Will update later today!
