### ISSUE TITLE
-bash: xcov: command not found

### ISSUE THREAD

**Issue by amitdhawan** [nakiostudio/xcov#65]
Hi,
I have installed gem xcov. But when i run the command xcov -w LystSDK.xcworkspace -s LystSDK -o xcov_output it gives -bash: xcov: command not found.

Please help.

**Comment by thelvis4** [comment]
Hi @amitdhawan,
As there are different potential causes to run into this issue, it would help us to know the following:
1. How did you install `xcov`? Using `gem install xcov` command or using `bundle install`?
2. What's the output when you run `which xcov` command?
3. What's the output after running `$PATH`?

**Comment by amitdhawan** [comment]
Its resolved now.

Thanks,
AD

From: Andrei Raifura
Reply-To: nakiostudio/xcov
Date: Monday, 26 December 2016 at 5:42 PM
To: nakiostudio/xcov
Cc: Amit Dhawan, Mention
Subject: Re: [nakiostudio/xcov] -bash: xcov: command not found (#65)


Hi @amitdhawan<https://github.com/amitdhawan>,
As there are different potential causes to run into this issue, it would help us to know the following:

  1.  How did you install xcov? Using gem install xcov command or using bundle install?
  2.  What's the output when you run which xcov command?
  3.  What's the output after running $PATH?

**Comment by thelvis4** [comment]
Ok, glad you figured it out.
