### ISSUE TITLE
The operation requires a selected developer portal team

### ISSUE THREAD

**Issue by Hellengo** [nakiostudio/xcov#66]
Xcode version: 8.2.1
Mac OS: 10.11.6
xcov version: xcov 0.12.5

$ xcodebuild -workspace Vodka.xcworkspace -scheme Vodka -destination 'platform=iOS Simulator,name=iPhone 6 Plus' -configuration Debug -derivedDataPath 'build' test
.....
	Executed 2 tests, with 0 failures (0 unexpected) in 411.383 (411.388) seconds
** TEST SUCCEEDED **

$ xcov -w Vodka.xcworkspace -s Vodka --configuration Debug -o xcov_output
[11:42:58]: $ xcodebuild -list -workspace Vodka.xcworkspace -configuration Debug
[11:42:59]: Skipping file blacklisting as no ignore file was found at path ./.xcovignore

+-----------------------------+-------------------+
|             Summary for xcov 0.12.5             |
+-----------------------------+-------------------+
| workspace                   | Vodka.xcworkspace |
| scheme                      | Vodka             |
| configuration               | Debug             |
| output_directory            | xcov_output       |
| html_report                 | true              |
| markdown_report             | false             |
| json_report                 | false             |
| minimum_coverage_percentage | 0                 |
| ignore_file_path            | ./.xcovignore     |
| include_test_targets        | false             |
| skip_slack                  | false             |
+-----------------------------+-------------------+

[11:42:59]: $ xcodebuild clean -showBuildSettings -workspace Vodka.xcworkspace -scheme Vodka -configuration Debug
2016-12-27 11:43:01.010 xcodebuild[17247:761697] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11758/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
    "group.com.beastbikes.ios"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7f9d8dc7f6a0>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7f9d8a50f020>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-12-27 11:43:01.014 xcodebuild[17247:761697] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11758/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
    "group.com.beastbikes.ios"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7f9d8dc7f6a0>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7f9d8a50f020>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
[11:43:01]: Unable to find any .xccoverage file.
[11:43:01]: Make sure you have enabled 'Gather code coverage' setting on your scheme settings.
[11:43:01]: Alternatively you can provide the full path to your .xccoverage file.

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

![image](https://cloud.githubusercontent.com/assets/7005423/21490050/4c9a25be-cc2b-11e6-840a-fe88e891c725.png)

**Comment by thelvis4** [comment]
@Hellengo Actually, `xcodebuild` is the one requiring a selected Developer Portal. `xcov` doesn't need it directly.

In this case, it seems like `xcov` couldn't find `.xccoverage` file because of the custom DerivedData path.
Please try to run `xcov` again specifying the DerivedData path.
Like so:
```
xcov -w Vodka.xcworkspace -s Vodka --configuration Debug -o xcov_output --derived_data_path 'build'
```

Also, to make sure `.xccoverage` file is generated you can run the tests with `-enableCodeCoverage YES` appended to `xcodebuild` command:
```
xcodebuild -workspace Vodka.xcworkspace -scheme Vodka -destination 'platform=iOS Simulator,name=iPhone 6 Plus' -configuration Debug -derivedDataPath 'build' -enableCodeCoverage YES test
```

**Comment by thelvis4** [comment]
@Hellengo Have you figured this out?

**Comment by Hellengo** [comment]
thx，yes it's succeeded. but the report has some questions, like this
![image](https://cloud.githubusercontent.com/assets/7005423/21561839/56e979e6-cead-11e6-9a51-aafa1596da52.png)
but really result like this

**Comment by thelvis4** [comment]
@Hellengo Can you please share with us `xcov`'s output and `.xcovignore` file (if there is one)?
