### ISSUE TITLE
only_project_targets option not working on 0.12.5

### ISSUE THREAD

**Issue by jhanzo** [nakiostudio/xcov#69]
Despite of description done in README.md, `--only_project_targets` is not available in xcov options.

Run `xcov -p MyApp.xcodeproj --only_project_targets` returns : 
> invalid option : --only_project_targets

**Comment by thelvis4** [comment]
@jhanzo This feature was implemented (and merged in master) after v0.12.5 and will be part of the next release (I suppose v0.13.0).
Because it's in master, you can see the option in README.

@nakiostudio Could we release a new version?

**Comment by nakiostudio** [comment]
Released `1.0.0` :)

Thanks @jhanzo and @thelvis4 🙌

**Comment by jhanzo** [comment]
Thanks a lot guys 👏 🚀
