### ISSUE TITLE
Case sensitivity needs to be handled in .xcovignore

### ISSUE THREAD

**Issue by manas-chaudhari** [nakiostudio/xcov#74]
I am running this on macOS. xcov version 1.0.0.

On my system, I have a directory named `Common`. It was renamed from `common` a while ago, and I had also updated the index on `git`. I want this directory to be ignored when using `xcov`. In `.xcovignore`, adding `Common` doesn't work. Strangely, adding `common` makes it work. 
I think this issue is because the file system on macOS is case insensitive.

I intend to commit `.xcovignore`, but doing that would likely break ignore functionality on other systems as the directory created for them would be `Common`.

**Comment by manas-chaudhari** [comment]
Turns out my pbxproj still contained old name :/
Fixed

**Comment by thelvis4** [comment]
I was about to push a solution for this already 😄 

I still think it's a good idea to compare case-insensitively as we cannot have `TestFolder` and `testfolder`. 🤔 
@nakiostudio what do you think about this?

**Comment by manas-chaudhari** [comment]
In case we don't want to compare case-insensitively, perhaps a line in documentation mentioning that xcov reads path from pbxproj would help.

**Comment by thelvis4** [comment]
Not sure what `reads path from pbxproj` means in this context. 🤔 
Can you give an example, please?

**Comment by manas-chaudhari** [comment]
Sure. Let me indicate the scenario where case sensitivity causes a problem.

In pbxproj file, the path value is `common/AppDelegate.swift`. It looks as follows:

```
EB5B31471E40617900EB190F /* AppDelegate.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; name = NetworkCommons.swift; path = common/AppDelegate.swift; sourceTree = SOURCE_ROOT; };
```

In my file system, and in git, the directory's name is `Common` with a capital `C`. In this scenario, if I want to ignore this file for code coverage, I need to add `common/AppDelegate.swift` in my `.xcovignore`. 

Thus, when I said `reads path from pbxproj`, I meant that xcov will match the ignore paths to the path values specified in `pbxproj` and not those on the file system.

Of course, we can assume that pbxproj and file system can differ only wrt case, otherwise the build would fail.

**Comment by thelvis4** [comment]
@manas-chaudhari Thanks for the example and a good explanation. 🙌

When this scenario happens, I believe, it would be easier to reason that matching ignored files/folders happens case sensitively than to dig into the project file to find out what's the case of the files/folders we want to ignore.
Suddenly, having case insensitive matching makes even more sense. 😄 
I will open the PR I planned to open yesterday.

**Comment by nakiostudio** [comment]
Thanks both @manas-chaudhari and @thelvis4 🙌 

I agree with you @thelvis4, simplicity FTW :)
