### ISSUE TITLE
Request for --hide-ignored-files option

### ISSUE THREAD

**Issue by getaaron** [nakiostudio/xcov#80]
Currently files ignored via `.xcovignore` are not *really* ignored — they appear as 0% coverage.

For example:

![image](https://cloud.githubusercontent.com/assets/789577/23226744/91757a16-f8eb-11e6-9855-f739a9f62ba3.png)

```
+-----------------------------------+----+
|          xcov Coverage Report          |
+-----------------------------------+----+
                – snip ✂️ –
| AFNetworking.framework            | 0% |
| OMGHTTPURLRQ.framework            | 0% |
+-----------------------------------+----+
```

However, I don't want to see these files at all.

Would be nice if there was a `--hide-ignored-files` option to completely remove this irrelevant stuff from the report.

**Comment by nakiostudio** [comment]
Hey @getaaron ! Sorry for the delay in my reply. These are targets therefore you should be able to ignore them using the option `exclude_targets`. i.e.

```ruby
    xcov(
      scheme: Lyst,
      workspace: Lyst.xcworkspace,
      output_directory: "./xcov_report",
      exclude_targets: "EasyPeasy.framework,AFNetworking.framework"
    )
```

**Comment by nmccann** [comment]
The `only_project_targets` parameter might also address this particular situation.
