### ISSUE TITLE
wrong number of arguments (given 0, expected 1)

### ISSUE THREAD

**Issue by valeriomazzeo** [nakiostudio/xcov#85]
Hi there,

Since upgrading to xcov `1.1.1`, I have started getting this error from fastlane:
`wrong number of arguments (given 0, expected 1)`

I am not sure what if it's something to do with how fastlane launch xcov or xcov directly.

Same issue as described here: https://github.com/fastlane/fastlane/issues/8407

Also, everything works on xcov `1.0.1`

**Comment by nakiostudio** [comment]
Hi @valeriomazzeo 👋 always super fast reporting issues!

Integration with Fastlane is broken until they release a new version including this change:
https://github.com/fastlane/fastlane/pull/8400

Hopefully it won't take long!

**Comment by valeriomazzeo** [comment]
good to know, thank you very much! :)

**Comment by nakiostudio** [comment]
This should be fixed now :)

**Comment by nakiostudio** [comment]
Confirmed 🎉 https://github.com/nakiostudio/EasyPeasy/pull/51
