### ISSUE TITLE
Specifing a destination to run tests on

### ISSUE THREAD

**Issue by Usipov** [nakiostudio/xcov#87]
Thanx for that noteworthy tool!

Did not find an analog to the `xcodebuild`'s parameter
```
-destination 'platform=iOS Simulator,name=iPhone SE,OS=10.2'
```

**Comment by nakiostudio** [comment]
Hi @Usipov 👋 

Thanks for your comment!

`xcov` doesn't run tests. It only takes the output of the latest tests pass and creates the report, for that reason set the destination is not really needed :)

**Comment by Usipov** [comment]
@nakiostudio, Thanks for the answer!
Looks like i misunderstood the API

I searched for a `xcov` parameter to specify a file to be scanned
```
xcov --file /path/to/reports.xccoverage
```

Instead i found parameters looking similar to those of `xcodebuild` command.
That's when i started considering the `xcov` as a wrapper around `xcodebuild`

I'm confused =)
