### ISSUE TITLE
Getting raw coverage value

### ISSUE THREAD

**Issue by ushisantoasobu** [nakiostudio/xcov#88]
Thank you for a gread work! But I have a question.

Is there any way for posting **raw coverage value** to Slack?
This means, for example, not `12%` but `12.45%`.

Maybe I need an option to avoid below codes.
https://github.com/nakiostudio/xcov/blob/b4d00172e7277adae5f28f8fe36c19af33600499/lib/xcov/model/base.rb#L13-L17

**Comment by nakiostudio** [comment]
Hi @ushisantoasobu 👋 

There is no way of doing that right now, I will default to that 👍

**Comment by nakiostudio** [comment]
Change included in `1.3.0` :)

**Comment by ushisantoasobu** [comment]
@nakiostudio Thank you so much!!! 😄
