### ISSUE TITLE
Hide ignored files on the HTML report

### ISSUE THREAD

**Issue by ArthurAlvarez** [nakiostudio/xcov#93]
Is there any way to hide the ignored files on the HTML report?
Currently they appear on the report having 0% coverage.

**Comment by nakiostudio** [comment]
Hi @ArthurAlvarez 👋 

Ignored files were supposed to appear greyed out, will take a look 👍

**Comment by nakiostudio** [comment]
@ArthurAlvarez this is how ignored files appear on my HTML reports.

![screenshot](https://user-images.githubusercontent.com/1814571/28239278-8e7540f4-6960-11e7-94ae-0e15cf455505.png)

Are you talking about the ignored files on the report or the target?

**Comment by ArthurAlvarez** [comment]
I was talking about the targets but I was able to solve this by using the 'exclude_targets' flag.

Thanks for the support!
