### ISSUE TITLE
Ignoring folders doesn't work

### ISSUE THREAD

**Issue by robertofrontado** [nakiostudio/xcov#94]
This is my setup:

Fastfile
```
desc "Coveralls"
lane :coveralls do
  xcov(
    project: "Project.xcodeproj",
    scheme: ENV["BITRISE_SCHEME"],
    coveralls_repo_token: ENV["COVERAGE_ACCESS_TOKEN"],
    ignore_file_path: "./.xcovignore"
  )  
end
```

.xcovignore
```
# .xcovignore.yml

# Ignore files
- PROJECT/folder/
- PROJECT/folder/*
- PROJECT/folder/*.swift
```

Is not ignoring the files at that folder, is that right? Or I'm doing it wrong

**Comment by kohtenko** [comment]
Same here. None of the options below work for me:
```
Pods
Pods/
Pods/*
```

**Comment by robertofrontado** [comment]
Yep I had to ignore every file 😞

**Comment by kohtenko** [comment]
Looking into the source code I can see that ignoring actually works well. Files that I wanted to ignore weren't listed in terminal during the execution because they don't added to the target. So coverage calculated without them even if they aren't in `.xcovignore`.
Don't know about your case though, @robertofrontado.

**Comment by nakiostudio** [comment]
Hi @robertofrontado @kohtenko :wave: 

Thanks for reporting! I'm digging into this right now 👍

**Comment by nakiostudio** [comment]
Can't reproduce the issue, the only thing that works funny is how the path to the `.xcovignore` file set by default.

This is my .xcovignore file:
```yaml
- Example/
- EasyPeasy/
```

And this is the result:
<table><tr>
<td>
<img width="859" alt="screen shot 2017-07-15 at 13 17 50" src="https://user-images.githubusercontent.com/1814571/28239277-8a005b3a-6960-11e7-92f9-c162bb9bb5e3.png"/>
</td>
<td>
<img width="1116" alt="screen shot 2017-07-15 at 13 18 17" src="https://user-images.githubusercontent.com/1814571/28239278-8e7540f4-6960-11e7-94ae-0e15cf455505.png">
</td>
</tr></table>

**Comment by robertofrontado** [comment]
@nakiostudio Strange thing, I tested it today again and using `Pods` it worked 🤔

So, I'll close this issue and reopen it again if needed 👍
